### ISSUE TITLE
'package:R.utils' may not be available when loading

### ISSUE THREAD

**Issue by joseah** [HenrikBengtsson/R.utils#19] opened 2015-04-18 22:04 UTC
When just loading the library, I got this warning message
```
Warning message:
In save(list = ls(envir = .GlobalEnv, all.names = TRUE), file = outfile,  :
  'package:R.utils' may not be available when loading
```
This is the code with session information.
```R
>library('R.utils')
>devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.1.1 Patched (2014-10-16 r66782)
 system   x86_64, linux-gnu                          
 ui       X11                                        
 language (EN)                                       
 collate  en_US.UTF-8                                
 tz       <NA>                                       

Packages ---------------------------------------------------------------------------------------------------------------
 package     * version date       source        
 devtools    * 1.7.0   2015-01-17 CRAN (R 3.1.1)
 R.methodsS3   1.7.0   2015-02-20 CRAN (R 3.1.1)
 R.oo          1.19.0  2015-02-28 CRAN (R 3.1.1)
 rstudioapi  * 0.2     2014-12-31 CRAN (R 3.1.1)
 R.utils       2.0.0   2015-03-01 CRAN (R 3.1.1)
> 
> proc.time()
   user  system elapsed 
  0.596   0.076   0.800 
Warning message:
In save(list = ls(envir = .GlobalEnv, all.names = TRUE), file = outfile,  :
  'package:R.utils' may not be available when loading
```
I'm runnning this script into a cluster as 
```bash
R CMD BATCH test_rutils.R
```
The package is loaded successfully and functions work correctly. 
How can I avoid this warning message?
Thanks.

**Comment by HenrikBengtsson** [comment] 2015-04-18 22:36
Do you see this also with?
```
R --vanilla CMD BATCH test_rutils.R
```
If not, what about?
```
R --no-restore-data CMD BATCH test_rutils.R
```
If the above avoids the warnings, then it's most likely due to a saved `.RData` file which holds a saved reference to R.utils.

If this doesn't help, see if you can reproduce it elsewhere, because if so, I need more information.

**Comment by joseah** [comment] 2015-04-18 23:35
I got the same warning, now in my own laptop running with ```--vanilla``` and ```--no-restore-data```.
Now the output of the script from my laptop with the 3.1.3 R version. 
```shell
R --no-restore-data CMD BATCH test_rutils.R
```
```
less test_rutils.Rout
```
```R

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Attempting to load the environment ‘package:R.utils’
Loading required package: R.methodsS3

Attaching package: ‘R.oo’

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, gc, load, save


Attaching package: ‘R.utils’

The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, inherits, isOpen, parse, warnings

[Previously saved workspace restored]

> library('R.utils')
> 
> options(width = 120)
> 
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.3 (2015-03-09)
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       <NA>                        

Packages ---------------------------------------------------------------------------------------------------------------
 package     * version date       source        
 devtools    * 1.7.0   2015-01-17 CRAN (R 3.1.2)
 R.methodsS3   1.7.0   2015-02-20 CRAN (R 3.1.3)
 R.oo          1.19.0  2015-02-28 CRAN (R 3.1.3)
 rstudioapi  * 0.2     2014-12-31 CRAN (R 3.1.2)
 R.utils       2.0.0   2015-03-01 CRAN (R 3.1.3)
> 
> proc.time()
   user  system elapsed 
  0.411   0.032   0.428 
Warning message:
In save(list = ls(envir = .GlobalEnv, all.names = TRUE), file = outfile,  :
  'package:R.utils' may not be available when loading
```

**Comment by joseah** [comment] 2015-04-19 00:05
Even when I delete .Rdata and .Rhistory, I got the same:
```shell
R --no-restore-data CMD BATCH test_rutils.R
```

```R

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library('R.utils')
Loading required package: R.oo
Loading required package: R.methodsS3
R.methodsS3 v1.7.0 (2015-02-19) successfully loaded. See ?R.methodsS3 for help.
R.oo v1.19.0 (2015-02-27) successfully loaded. See ?R.oo for help.

Attaching package: ‘R.oo’

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, gc, load, save

R.utils v2.0.0 (2015-02-28) successfully loaded. See ?R.utils for help.

Attaching package: ‘R.utils’

The following object is masked from ‘package:utils’:

    timestamp

The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, inherits, isOpen, parse, warnings

> 
> options(width = 120)
> 
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.3 (2015-03-09)
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       <NA>                        

Packages ---------------------------------------------------------------------------------------------------------------
 package     * version date       source        
 devtools    * 1.7.0   2015-01-17 CRAN (R 3.1.2)
 R.methodsS3   1.7.0   2015-02-20 CRAN (R 3.1.3)
 R.oo          1.19.0  2015-02-28 CRAN (R 3.1.3)
 rstudioapi  * 0.2     2014-12-31 CRAN (R 3.1.2)
 R.utils       2.0.0   2015-03-01 CRAN (R 3.1.3)
> 
> proc.time()
   user  system elapsed 
  0.481   0.019   0.485 
Warning message:
In save(list = ls(envir = .GlobalEnv, all.names = TRUE), file = outfile,  :
  'package:R.utils' may not be available when loading
```

**Comment by HenrikBengtsson** [comment] 2015-04-19 01:05
This is helpful.  I think a minimal reproducible example, except for the `suppressPackageStartupMessages()` not really needed, of what's going on is.

# Rscript
```r
$ Rscript -e "suppressPackageStartupMessages(library(R.utils)); quit('yes')"
Warning message:
In save(list = names(.GlobalEnv), file = outfile, version = version,  :
  'package:R.utils' may not be available when loading
```
Note that it does not happen if the session is _not_ saved at the end, i.e.
```r
$ Rscript -e "suppressPackageStartupMessages(library(R.utils)); quit('no')"
```
For non-interactive session, not doing an explicit `quit()` call is the same as calling `quit('default')`, where the default behavior is controlled by command-line options when calling `Rscript`.  This is why
```r
$ Rscript -e "suppressPackageStartupMessages(library(R.utils))"
```
does not generate the warning, but
```r
$ Rscript --save -e "suppressPackageStartupMessages(library(R.utils))"
Warning message:
In save(list = names(.GlobalEnv), file = outfile, version = version,  :
  'package:R.utils' may not be available when loading
```
does.

# R

Now lets try `R` instead of `Rscript`.  The default is the same:
```r
$ rm .RData ## Just in case
$ R --quiet -e "suppressPackageStartupMessages(library(R.utils))"
> suppressPackageStartupMessages(library(R.utils))
>
>
```
but you get the warning with:
```r
$ rm .RData ## Just in case
$ R --quiet --save -e "suppressPackageStartupMessages(library(R.utils))"
> suppressPackageStartupMessages(library(R.utils))
>
>
Warning message:
In save(list = names(.GlobalEnv), file = outfile, version = version,  :
  'package:R.utils' may not be available when loading
```

# R CMD BATCH
Finally, what about `R CMD BATCH`?
```r
# Create test.R file with the above call
$ echo suppressPackageStartupMessages(library(R.utils)) > test.R
```
Here we get the warning:
```r
$ R CMD BATCH test.R
$ tail -3 test.Rout
[HB-X201]{hb}: tail -3 test.Rout
Warning message:
In save(list = names(.GlobalEnv), file = outfile, version = version,  :
  'package:R.utils' may not be available when loading
```
It's interesting to note that `R --no-save CMD BATCH test.R` still saves the session; not sure if that is a bug or a feature.

# Conclusion
The warning occurs because the R session is saved at the end and there is an object in the R session that "is tied" (formally a promise) to the R.utils package environment.  This object is created by R.utils currently out of control by the user.  I've created Issue #20 to see if it's possible to avoid this all together.

If the session does not need to be saved, a (verified) workaround for avoiding the warning is to explicitly quit the R script using `quit(save="no")` at the very end.

Another workaround is to do `environment(.Last) <- globalenv()` at the very end.  For more details, see Issue #20.

Thxs

**Comment by joseah** [comment] 2015-04-19 02:29
Thank you so much for your explanation and suggestions. ```quit(save="no")``` seems a good solution for now. I really like this package. Thanks again.

**Comment by HenrikBengtsson** [comment] 2015-04-19 02:31
Good to hear.

FYI, I think I've solved it; the fix will be part of the next package release.

**Closed by HenrikBengtsson** 2015-04-19 02:31 UTC
Labels: question

**Comment by s-fleck** [comment] 2018-12-24 11:05
Im experiencing this issue in RStudio 1.2.192
